SELECT F.PRODUCT_ID, PRODUCT_NAME, (F.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT F, (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
                      FROM FOOD_ORDER
                      WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM-DD') LIKE '2022-05%'
                      GROUP BY PRODUCT_ID) O
WHERE F.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, F.PRODUCT_ID ASC