SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H, CAR_RENTAL_COMPANY_CAR C
WHERE H.CAR_ID = C.CAR_ID AND TO_CHAR(H.START_DATE, 'MM') = '10' AND C.CAR_TYPE = '세단'
ORDER BY C.CAR_ID DESC