SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM animal_outs
WHERE ANIMAL_ID IN (SELECT ANIMAL_ID
               FROM ANIMAL_INS
               WHERE SEX_UPON_INTAKE LIKE 'Intact%')
AND NOT SEX_UPON_OUTCOME LIKE 'Intact%'