SELECT TO_CHAR(O.SALES_DATE, 'YYYY') AS YEAR, TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')) AS MONTH, COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS,
ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*)
                                   FROM USER_INFO
                                   WHERE TO_CHAR(JOINED, 'YYYY') = '2021'), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE O, USER_INFO U
WHERE O.USER_ID = U.USER_ID AND TO_CHAR(U.JOINED, 'YYYY') = '2021'
GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM')
ORDER BY YEAR, MONTH