SELECT F.CATEGORY, F.PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F, (SELECT CATEGORY, MAX(PRICE) AS MPRICE
                      FROM FOOD_PRODUCT
                      WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY) T
WHERE F.CATEGORY = T.CATEGORY AND F.PRICE = T.MPRICE
ORDER BY F.PRICE DESC