SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (SELECT I.ANIMAL_ID
                   FROM ANIMAL_INS I, ANIMAL_OUTS O
                   WHERE I.ANIMAL_ID = O.ANIMAL_ID)
ORDER BY ANIMAL_ID, NAME
                   