SELECT ANIMAL_ID, NAME
FROM (SELECT I.ANIMAL_ID, I.NAME, O.DATETIME-I.DATETIME AS TIME
      FROM ANIMAL_INS I, ANIMAL_OUTS O
      WHERE I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY TIME DESC)
WHERE ROWNUM <= 2