SELECT A.HOUR, NVL(A.COUNT + B.COUNT, 0) AS COUNT
FROM (SELECT LEVEL-1 AS HOUR, 0 COUNT
    FROM DUAL CONNECT BY LEVEL <= 24) A
    LEFT OUTER JOIN
    (SELECT HOUR, COUNT(*) AS COUNT
    FROM (SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
          FROM ANIMAL_OUTS
         )
    GROUP BY HOUR) B
    ON A.HOUR = B.HOUR
ORDER BY A.HOUR ASC