SELECT I.ANIMAL_ID, I.NAME
FROM (SELECT I.ANIMAL_ID, I.NAME, I.datetime AS INDATE
      FROM ANIMAL_INS I, ANIMAL_OUTS O
      WHERE I.ANIMAL_ID = O.ANIMAL_ID) I,
     (SELECT I.ANIMAL_ID, I.NAME, O.datetime AS OUTDATE
      FROM ANIMAL_INS I, ANIMAL_OUTS O
      WHERE I.ANIMAL_ID = O.ANIMAL_ID) O
WHERE I.ANIMAL_ID = O.ANIMAL_ID AND I.INDATE > O.OUTDATE
ORDER BY I.INDATE