SELECT CAR_ID, ROUND(SUM(END_DATE-START_DATE+1) / COUNT(*), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
GROUP BY CAR_ID
HAVING ROUND(SUM(END_DATE-START_DATE+1) / COUNT(*), 1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC