SELECT A.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM AUTHOR A, (SELECT B.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE*T.SP) AS TOTAL_SALES
                FROM BOOK B, (SELECT BOOK_ID, SUM(SALES) AS SP
                              FROM BOOK_SALES
                              WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
                GROUP BY BOOK_ID) T
                WHERE B.BOOK_ID = T.BOOK_ID
                GROUP BY B.AUTHOR_ID, B.CATEGORY) K
WHERE A.AUTHOR_ID = K.AUTHOR_ID
ORDER BY A.AUTHOR_ID ASC, CATEGORY DESC