SELECT K.FLAVOR
FROM (SELECT F.FLAVOR AS FLAVOR, (F.TOTAL_ORDER + J.TOTAL_ORDER) AS TOTAL_ORDER
        FROM FIRST_HALF F,
            (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
             FROM JULY
             GROUP BY FLAVOR) J
        WHERE F.FLAVOR = J.FLAVOR
        ORDER BY TOTAL_ORDER DESC) K
WHERE ROWNUM <= 3