SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, T.maxi
FROM REST_INFO R, (SELECT FOOD_TYPE, MAX(FAVORITES) AS maxi
                   FROM REST_INFO
                   GROUP BY FOOD_TYPE) T
WHERE R.FOOD_TYPE = T.FOOD_TYPE AND R.FAVORITES = T.maxi
ORDER BY FOOD_TYPE DESC