SELECT APNT_NO, PT_NAME, O.PT_NO, O.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT P, DOCTOR D, (SELECT *
                           FROM APPOINTMENT
                           WHERE TO_CHAR(APNT_YMD, 'YYYYMMDD') = 20220413
                           AND APNT_CNCL_YN = 'N') O
WHERE P.PT_NO = O.PT_NO AND D.DR_ID = O.MDDR_ID
ORDER BY APNT_YMD