SELECT B.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK B, (SELECT BOOK_ID, SUM(SALES) AS SALES
              FROM BOOK_SALES
              WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
              GROUP BY BOOK_ID) T
WHERE B.BOOK_ID = T.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC